/* ═══════════════════════════════════════════════════════
   NOXARA CODEX — Merkezi veri (codex.html + palette + tooltip)
   v1.14.0.54 — 60+ node, 11 kategori
═══════════════════════════════════════════════════════ */
window.CODEX_KATEGORILER = [
  { id:'unite',  isim:'Üniteler',  ikon:'⚔️', renk:'#e74c3c' },
  { id:'bina',   isim:'Binalar',   ikon:'🏛️', renk:'#c9a84c' },
  { id:'kaynak', isim:'Kaynaklar', ikon:'💎', renk:'#3498db' },
  { id:'savas',  isim:'Savaş',     ikon:'🛡️', renk:'#9b59b6' },
  { id:'buyu',   isim:'Büyüler',   ikon:'🔮', renk:'#8e44ad' },
  { id:'casus',  isim:'Casus',     ikon:'🕵️', renk:'#2ecc71' },
  { id:'cag',    isim:'Çağ',       ikon:'⏳', renk:'#f39c12' },
  { id:'moral',  isim:'Moral',     ikon:'😊', renk:'#1abc9c' },
  { id:'guild',  isim:'Guild',     ikon:'🏰', renk:'#16a085' },
  { id:'kadim',  isim:'Kadim',     ikon:'🏺', renk:'#d4af37' },
  { id:'irk',    isim:'Irklar',    ikon:'👑', renk:'#e67e22' },
];

window.CODEX_NODES = [
  // ═══ UNITELER (11) ═══
  { id:'piyade', baslik:'Piyade', kategori:'unite', tier:'T1', ikon:'🗡️',
    ozet:'Hafif piyade. Her krallığın ilk savaş birimi.',
    stats:{ ATK:2, DEF:10, Zirh:20, İska:10, Maaş:20, Tur:'4-6' },
    quote:'Sayılar bazen zırhdan daha keskindir.',
    aciklama:'Piyade, Noxara savaş alanının temel taşıdır. Köy oğullarından toplanır, küçük bir altın karşılığı hızla eğitilir ve öncü saflara dizilir.\n\nDüşük saldırı ve orta zırhla göz kamaştırmaz — ama ucuzluğu ve hızlı üretimi sayesinde her büyük ordunun omurgasıdır. Hiçbir kral sadece ejderhayla savaşmaz; piyade olmadan ordu düzeni kurulmaz.',
    detay:'**Savaş Turu**: Tur 4-6\'da saldırır. İlk 3 tur yalnız zırhıyla darbe alır, sonra hasar vermeye başlar.\n\n**Saf Tercihi**: Saf 1 veya 2. Ön saf olunca okçu ve büyücü gibi arka saf birimleri korur. Arka safa konulursa düşman birliğe ulaşana kadar beklemede kalır.\n\n**Maliyet**: 1 asker + 20 altın + 20 altın maaş/saat. Tier farketmez — her asker 1 altın.\n\n**Zırh mekanizması (v1.14.0.45)**: Zirh 20 → gelen hasara `/ (1 + 20/50) = %29 azaltma` uygular. Paladinden daha az ama ucuzdur.',
    strateji:[
      'Tek başına asla gönderme. 100 piyade = bir okçu ordusunun yemi.',
      'Okçuyla eş zamanlı kullan: piyade ön saf, okçu arka saf — en klasik açılış.',
      'Çağ 1-2 savaşlarda belkemiği; Çağ 3+ Şövalye/Paladinle değiştirilir.',
      'Yağma savaşlarında sayıca avantajı kullan — maliyeti düşük olduğundan kayıplar az acı verir.'
    ],
    ipucu:'Oduncu/Tarla/Ev kurduktan hemen sonra en az 50 piyade eğit. Bu senin ilk savunma hattın olur.',
    dikkat:'Piyade zırhı orta (20) olduğundan Büyücü, Işığın Savaşçısı gibi elit saldırı birimleri karşısında kitlesel kayıp verir. Ejderha varsa piyade yemdir.',
    baglantilar:[{id:'asker',tip:'gereklilik'},{id:'altin',tip:'gereklilik'},{id:'savas-saf',tip:'ilgili'},{id:'okcu',tip:'karsilastir'},{id:'sovalye',tip:'karsilastir'},{id:'zirh-iska',tip:'ilgili'}]},

  { id:'okcu', baslik:'Okçu', kategori:'unite', tier:'T1', ikon:'🏹',
    ozet:'Menzilli birim. Arka saftan ateş eder.',
    stats:{ ATK:5, DEF:12, Zirh:10, İska:20, Maaş:28, Tur:'1-3' },
    quote:'Uzaktan vuran galip gelir, yakında savaşan hayatta kalır.',
    aciklama:'Okçu, Noxara\'nın uzun menzilli gözü ve ödünsüz el ustasıdır. Tur 1\'den itibaren saldırır, düşman piyadesine yaklaşmasına fırsat vermeden kayıp verdirir.\n\nZırhı düşük olduğu için yakın döğüşte kırılgandır — mutlaka bir ön-saf piyade veya şövalye ile korunmalıdır.',
    detay:'**Savaş Turu**: Tur 1-3. Menzilli birim olduğu için düşman ön safa ulaşmadan vurur.\n\n**İska (v1.14.0.45)**: %20 deterministik — her tur `atk × 0.8` verir. Simülatörde tutarlı.\n\n**Kule Sinerjisi**: Okçu Kulesi savaşa sanal okçu birimi ekler — kulen varsa saldırıda +50 ATK bedavaya gelir.\n\n**Zırh avı**: Zirh 10 çok düşük, piyade veya şövalyeyi önde tutman gerekir.',
    strateji:[
      'Saf 3-4\'e koy. Piyade/şövalye ön tarafta düşmanı tutarken sen arkadan biçersin.',
      'Büyücü ile beraber kullan — büyücü mana ile saldırırken okçu oklarla tamamlar.',
      'Savunmada üstün: düşman gelirken 3 tur boyunca sürekli hasar verir.',
      'Saldırıda seni yakından tanıyan biriyle gitme: Şövalye/Paladinle ön-arka dengesi kur.'
    ],
    ipucu:'Karışık savaşta 100 piyade + 30 okçu karması, saf 100 piyade ordusunu rahat yener.',
    dikkat:'Zırhı 10 çok düşük — saf 1\'e asla koyma, düşmanın ilk saldırısında erir.',
    baglantilar:[{id:'asker',tip:'gereklilik'},{id:'zirh-iska',tip:'ilgili'},{id:'piyade',tip:'karsilastir'},{id:'kule-okcu',tip:'ilgili'},{id:'savas-saf',tip:'ilgili'}]},
  { id:'savasci', baslik:'Savaşçı', kategori:'unite', tier:'T2', ikon:'⚔️',
    ozet:'Orta agirlik. Daha dayanikli piyade.',
    stats:{ ATK:6, DEF:18, Zirh:25, İska:20, Maaş:32 },
    baglantilar:[{id:'altin',tip:'gereklilik'},{id:'asker',tip:'gereklilik'},{id:'kolcu',tip:'karsilastir'},{id:'kolcu',tip:'sonra'},{id:'metal',tip:'gereklilik'},{id:'piyade',tip:'sonra'},{id:'savas-saf',tip:'ilgili'}]},
  { id:'sovalye', baslik:'Şövalye', kategori:'unite', tier:'T2', ikon:'🐴',
    ozet:'Ağır süvari. Çağ 2+ at gerektirir.',
    stats:{ ATK:6, DEF:22, Zirh:20, İska:15, Maaş:40, Tur:'4-6' },
    quote:'Atım zırhım, mızrağım sözüm.',
    aciklama:'Şövalye, 2. Çağ\'ın saygın askeri. Piyadeye oranla üç kat dayanıklı, iki kat maliyetli. Savaş alanında saygı uyandıran atlı kuvvet.\n\nAhır olmadan şövalye üretilmez; 1 at + 1 asker + altın maliyeti ödendiğinde saf 2-3\'te demir bir duvar oluşturur.',
    detay:'**Açılış**: Çağ 2. Ahır binası kurulduktan sonra üretilir.\n\n**Maliyet**: 1 at + 1 asker + 40 altın + 40 altın/saat maaş. At nadir kaynak olduğundan şövalye ordusu ekonomiyi zorlar.\n\n**Def değeri yüksek (22)**: Piyade (10) ve Okçu (12) karşısında ciddi dayanıklılık. Zırh 20 → %29 azaltma.\n\n**Tek zayıflık**: Yüksek maaş. 1000 şövalye/saat = 40K altın.',
    strateji:[
      'Piyade ön, şövalye orta saf (2-3). Düşman piyadesi ön safa vurup eridikçe şövalye işi bitirir.',
      'Okçu arkada + şövalye ortada = dengeli karma ordu.',
      'Sadece şövalye ordusu = maaş bombası. 100 şövalye/saat = 4K altın. Biraz piyade karıştır.',
      'Kadim Aurium\'dan at al — üretimi hızlandır, ama 240 PG sonra saldırıya hazır ol.'
    ],
    ipucu:'Ahırı kur kurmaz 50 şövalye eğit. 150 Piyade + 50 Şövalye = ilk savaş galiplerinden.',
    dikkat:'At ekonomisine dikkat. Ahırın az at üretir, şövalye üretimi bekleyebilir.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2},ipucu:'2. Çağa geç, ardından Ahır kur'},
    baglantilar:[{id:'at',tip:'gereklilik'},{id:'ahir',tip:'gereklilik'},{id:'piyade',tip:'karsilastir'},{id:'paladin',tip:'sonra'},{id:'savas-saf',tip:'ilgili'}]},
  { id:'suvari', baslik:'Süvari', kategori:'unite', tier:'T2', ikon:'🏇',
    ozet:'Hizli saldiri birimi.',
    stats:{ ATK:8, DEF:26, Zirh:20, İska:15, Maaş:40 },
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'ahir',tip:'gereklilik'},{id:'altin',tip:'gereklilik'},{id:'asker',tip:'gereklilik'},{id:'at',tip:'gereklilik'},{id:'savas-saf',tip:'ilgili'},{id:'sovalye',tip:'karsilastir'}]},
  { id:'paladin', baslik:'Paladin', kategori:'unite', tier:'T3', ikon:'⚜️',
    ozet:'Elit ağır piyade. Yeminli kutsal birimler.',
    stats:{ ATK:9, DEF:33, Zirh:35, İska:20, Maaş:52 },
    quote:'Kalbim altın, kılıcım ateş — karanlığı bölmeye yemin ettim.',
    aciklama:'Paladin, iyi tarafın 3. Çağ elit birimidir. Kutsal yemin etmiş savaşçı-rahipler — yüksek zırhı ve def\'i ile gerçek bir tank.\n\nv1.14.0.45 zırh reformu sonrası paladin gerçekten tanklık yapıyor: her birim kendi zırhıyla hasar emer, paladin piyadeden 3 kat az hasar alır.',
    detay:'**Zırh Formülü**: Zirh 35 → gelen hasar `/ (1 + 35/50) = %41 azaltma`. Paladin 10000 hasar alınca sadece ~5900 içeri sızar.\n\n**Karşılaştırma**: Piyade (20 zırh, %29 azaltma), Şövalye (20 zırh, %29), Paladin (35, %41), Ejderha (70, %58).\n\n**İyi taraf kilidi**: Sadece İnsan/Elf/Cüce/Bucukluk üretebilir. Kötü tarafın eşdeğeri: Kara Şövalye veya Golem.\n\n**Yüksek maliyet**: 52 altın/saat maaş + üretim altını + islenmiş metal.',
    strateji:[
      'Saf 2-3\'te ön hat. Düşman saldırısını emer, arka saftaki büyücü/okçu korur.',
      'Düşman ejderhaya karşı etkili — yüksek zırh ejderhanın brute force hasarını azaltır.',
      'Paladin + İşığın Savaşçısı = T3+T4 elit çekirdek.',
      'Sadece paladinden ordu kurma — saf 4\'te farklı birim olmalı (okçu/büyücü).'
    ],
    ipucu:'3. Çağda 50 paladinlik ordu, 200 piyadelik orduya denk savunma sağlar ve daha az kaynak tüketir.',
    dikkat:'Kötü taraf oyuncusu paladinin karşılığını Kara Şövalye/Golem ile üretir — ırk seçiminde taraf kilidi var.',
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'sovalye',tip:'karsilastir'},{id:'zirh-iska',tip:'ilgili'},{id:'isin-savasci',tip:'sonra'},{id:'irk',tip:'ilgili'}]},
  { id:'kolcu', baslik:'Kolcu', kategori:'unite', tier:'T3', ikon:'🗡️',
    ozet:'Elit piyade, savasci sonrasi.',
    stats:{ ATK:10, DEF:30, Zirh:25, İska:20, Maaş:76 },
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'altin',tip:'gereklilik'},{id:'asker',tip:'gereklilik'},{id:'islenmis',tip:'gereklilik'},{id:'metal',tip:'gereklilik'},{id:'savas-saf',tip:'ilgili'},{id:'savasci',tip:'sonra'}]},
  { id:'buyucu', baslik:'Büyücü', kategori:'unite', tier:'T3', ikon:'🧙',
    ozet:'Saf 3-4 elit birim, mana kullanir.',
    stats:{ ATK:11, DEF:18, Zirh:20, İska:15, Maaş:120 },
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'altin',tip:'gereklilik'},{id:'asker',tip:'gereklilik'},{id:'buyu-sistem',tip:'ilgili'},{id:'buyucu-kulesi',tip:'gereklilik'},{id:'buyucu-kulesi',tip:'ilgili'},{id:'mana-beyaz',tip:'gereklilik'},{id:'savas-saf',tip:'ilgili'}]},
  { id:'isin-savasci', baslik:'Işığın Savaşçısı', kategori:'unite', tier:'T4', ikon:'✨',
    ozet:'Elit iyi taraf savaşçısı.',
    stats:{ ATK:40, DEF:100, Zirh:40, İska:10 },
    aciklama:'Sadece iyi taraf üretebilir. Kötü taraf eşdeğeri: Gölge Savaşçısı.',
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'altin',tip:'gereklilik'},{id:'asker',tip:'gereklilik'},{id:'golge-savasci',tip:'karsilastir'},{id:'irk',tip:'ilgili'},{id:'islenmis',tip:'gereklilik'},{id:'mana-beyaz',tip:'gereklilik'},{id:'paladin',tip:'karsilastir'}]},
  { id:'golge-savasci', baslik:'Gölge Savaşçısı', kategori:'unite', tier:'T4', ikon:'🌑',
    ozet:'Elit kotu taraf savasciisi.',
    stats:{ ATK:40, DEF:100, Zirh:40, İska:10 },
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'altin',tip:'gereklilik'},{id:'asker',tip:'gereklilik'},{id:'irk',tip:'ilgili'},{id:'isin-savasci',tip:'karsilastir'},{id:'islenmis',tip:'gereklilik'},{id:'mana-kirmizi',tip:'gereklilik'}]},
  { id:'ejderha', baslik:'Ejderha (4 tip)', kategori:'unite', tier:'T4', ikon:'🐉',
    ozet:'Nadir üzeri nadir — savaş alanında tanrı.',
    stats:{ ATK:'7500-10000', DEF:'2500-5000', Zirh:'70-75', Maaş:250 },
    quote:'Ejderhayı görmek, kralın iki kez düşünmesini sağlar.',
    aciklama:'Ejderha, Noxara evrenin en güçlü birimidir. Tek bir ejderha, yüzlerce piyadeye denktir. Ama maliyeti aynı oranda devasa: büyülü yumurta, nadir mağara girişimi, uzun üretim süresi.\n\n**4 tip**:\n- 🔵 **Mavi Ejderha** (iyi, ATK 7500) — buz nefesi\n- 🟡 **Altın Ejderha** (iyi, ATK 10000) — kutsal ateş\n- 🔴 **Kırmızı Ejderha** (kötü, ATK 7500) — volkan nefesi\n- ⚫ **Siyah Ejderha** (kötü, ATK 10000) — karanlık kor',
    detay:'**Kaynak**: Büyülü Tarla (düzenli yumurta) veya Mağara (nadir sansli yumurta). Kadim şehirler ejderha evcilleştirmenin hikaye kaynağıdır.\n\n**Zırh**: 70-75. Formül: `/ (1 + 70/50) = %58 azaltma`. Gelen hasarın yarısından fazlasını emer.\n\n**Maaş yok**: 250 altın/saat değil, aslında 0 maaş — ama üretim maliyeti o kadar yüksek ki tek ejderhaya 100 piyade kadar kaynak gider.\n\n**Saf**: Her saf ile uyumlu — ama arka safa (3-4) konulması korumasını maksimize eder.',
    strateji:[
      '3-5 ejderhalık bir ordu, saldırıda efsane yaratır.',
      'Düşman paladin/kolcu orduyu ejderhanın brute ATK\'si biçer.',
      'Tek ejderha kuleye karşı savunmasız — okçu/balista kulesi 240 ATK sanal birim ekliyor.',
      'Ejderhayı kaybetmek = yüzlerce saatlik kaynak kaybı. Tedbirli kullan.'
    ],
    ipucu:'İlk ejderhanı muhafazaya al — saf 4\'te sakla, tek başına keşif gönderme.',
    dikkat:'Ejderha maaş öderse ordu morali ile ilgili, ama BÜYÜK iska riski ile çalışır. İska orta ama bir darbe kaybedersen ciddi hasar.',
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'buyulu-yumurta',tip:'gereklilik'},{id:'magara',tip:'ilgili'},{id:'kadim',tip:'ilgili'},{id:'zirh-iska',tip:'ilgili'},{id:'irk',tip:'ilgili'}]},

  // ═══ BINALAR (14) ═══
  { id:'ev', baslik:'Ev', kategori:'bina', ikon:'🏠',
    ozet:'10 nüfus kapasitesi.', stats:{ Nüfus:10 },
    baglantilar:[{id:'koy',tip:'sonra'},{id:'koylu',tip:'ilgili'},{id:'nufus',tip:'saglar'}]},
  { id:'koy', baslik:'Köy', kategori:'bina', ikon:'🏘️',
    ozet:'100 nüfus. 20 Köy → 1 Kasaba + 5 doğum bonusu.', stats:{ Nüfus:100 },
    aciklama:'Eski Palantis kuralı: 20 köy birleştirilebilir → kasaba + doğum bonusu.',
    baglantilar:[{id:'ev',tip:'sonra'},{id:'kasaba',tip:'sonra'},{id:'nufus',tip:'saglar'}]},
  { id:'kasaba', baslik:'Kasaba', kategori:'bina', ikon:'🏯',
    ozet:'2000 nüfus. Büyük yerleşim.', stats:{ Nüfus:2000 },
    baglantilar:[{id:'isci',tip:'ilgili'},{id:'koy',tip:'sonra'},{id:'nufus',tip:'saglar'}]},
  { id:'oduncu', baslik:'Oduncu Kampı', kategori:'bina', ikon:'🌲',
    ozet:'Odun üretir. Başlangıç binası.',
    stats:{ Üretim:'10/PG/işçi', Kapasite:'40 oduncu' },
    aciklama:'Yeni oyuncuya 2 oduncu kampı verilir. Her oduncu işçisi saatte 10 odun getirir.',
    baglantilar:[{id:'isci',tip:'gereklilik'},{id:'kereste',tip:'ilgili'},{id:'odun',tip:'saglar'}]},
  { id:'tarla', baslik:'Tarla', kategori:'bina', ikon:'🌾',
    ozet:'Çiftçi kapasitesi + buğday.',
    stats:{ Kapasite:'50 çiftçi/tarla', Üretim:'8/PG/çiftçi' },
    aciklama:'Tarla yoksa çiftçi atanamaz.',
    baglantilar:[{id:'bugday',tip:'saglar'},{id:'isci',tip:'gereklilik'},{id:'koylu',tip:'ilgili'}]},
  { id:'balikci', baslik:'Balıkçı', kategori:'bina', ikon:'🎣',
    ozet:'Balıkçı kapasitesi + balık.',
    aciklama:'Balıkçılar 4-8-12-16-20-24. Palantis günlerinde üretim yapar.',
    baglantilar:[{id:'balik',tip:'saglar'},{id:'firin',tip:'ilgili'},{id:'isci',tip:'gereklilik'},{id:'nufus',tip:'ilgili'}]},
  { id:'ocak', baslik:'Ocak', kategori:'bina', ikon:'⛰️',
    ozet:'Metal madeni.', baglantilar:[{id:'isci',tip:'gereklilik'},{id:'isleme',tip:'sonra'},{id:'metal',tip:'saglar'}]},
  { id:'isleme', baslik:'İşleme', kategori:'bina', ikon:'🔨',
    ozet:'Metal → İşlenmiş Metal.',
    baglantilar:[{id:'islenmis',tip:'saglar'},{id:'kereste',tip:'ilgili'},{id:'metal',tip:'gereklilik'}]},
  { id:'firin', baslik:'Fırın', kategori:'bina', ikon:'🥖',
    ozet:'Buğday → Ekmek, Balık → Pişmiş.',
    baglantilar:[{id:'balik',tip:'gereklilik'},{id:'bugday',tip:'gereklilik'},{id:'isci',tip:'gereklilik'},{id:'sehir-moral',tip:'ilgili'}]},
  { id:'ahir', baslik:'Ahır', kategori:'bina', ikon:'🐎',
    ozet:'At ve kurt üretir. Süvari temeli.',
    stats:{ Üretim:'%0.1/saat', Çağ:'≥2' },
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'at',tip:'saglar'},{id:'kurt',tip:'saglar'},{id:'sovalye',tip:'ilgili'},{id:'suvari',tip:'ilgili'}]},
  { id:'lonca', baslik:'Lonca', kategori:'bina', ikon:'🎭',
    ozet:'Gizlilik üretir. Casus ekonomisi.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'casus-sistem',tip:'ilgili'},{id:'gizlilik',tip:'saglar'},{id:'isci',tip:'gereklilik'}]},
  { id:'buyulu-tarla', baslik:'Büyülü Tarla', kategori:'bina', ikon:'🌱',
    ozet:'Büyülü yumurta — ejderha için.',
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'buyulu-yumurta',tip:'saglar'},{id:'ejderha',tip:'ilgili'},{id:'mana-yesil',tip:'ilgili'}]},
  { id:'magara', baslik:'Mağara', kategori:'bina', ikon:'🕳️',
    ozet:'Nadir ejderha yumurtası.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'buyulu-yumurta',tip:'saglar'},{id:'ejderha',tip:'ilgili'},{id:'kadim',tip:'karsilastir'}]},
  { id:'tapinak-rathe', baslik:'Rathe Tapınağı (Beyaz)', kategori:'bina', ikon:'⛪',
    ozet:'Beyaz worshipper → Beyaz mana.',
    aciklama:'Worshipper geri döndürülemez. Her worshipper 0.1 mana/saat. Bilge 2x verir.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'bilge',tip:'ilgili'},{id:'buyucu-kulesi',tip:'ilgili'},{id:'koylu',tip:'gereklilik'},{id:'mana-beyaz',tip:'saglar'}]},
  { id:'tapinak-xegony', baslik:'Xegony Tapınağı (Mavi)', kategori:'bina', ikon:'💠',
    ozet:'Mavi mana — buz/soğuk okulu.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'buyucu-kulesi',tip:'ilgili'},{id:'koylu',tip:'gereklilik'},{id:'mana-mavi',tip:'saglar'}]},
  { id:'tapinak-fennin', baslik:'Fennin Tapınağı (Kırmızı)', kategori:'bina', ikon:'🔥',
    ozet:'Kırmızı mana — ateş/saldırı okulu.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'buyucu-kulesi',tip:'ilgili'},{id:'koylu',tip:'gereklilik'},{id:'mana-kirmizi',tip:'saglar'}]},
  { id:'tapinak-tunare', baslik:'Tunare Tapınağı (Yeşil)', kategori:'bina', ikon:'🌿',
    ozet:'Yeşil mana — doğa/üretim okulu.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'buyucu-kulesi',tip:'ilgili'},{id:'koylu',tip:'gereklilik'},{id:'mana-yesil',tip:'saglar'}]},
  { id:'buyucu-kulesi', baslik:'Büyücü Kulesi', kategori:'bina', ikon:'🗼',
    ozet:'Büyü öğrenme + hazırlama.',
    stats:{ MaxAdet:5 },
    aciklama:'1 kule = Çağ 1 büyüleri, 5 kule = Çağ 5. 28 büyü, 10 kademe.',
    baglantilar:[{id:'buyu-sistem',tip:'ilgili'},{id:'buyu-sistem',tip:'saglar'},{id:'buyucu',tip:'ilgili'},{id:'mana-beyaz',tip:'gereklilik'},{id:'parsomen',tip:'ilgili'}]},
  { id:'surlar', baslik:'Surlar', kategori:'bina', ikon:'🏰',
    ozet:'Kale savunması — saldırıda %20 zirh bonusu.',
    baglantilar:[{id:'kale-bonus',tip:'saglar'},{id:'kule-okcu',tip:'ilgili'},{id:'savas-motor',tip:'ilgili'}]},
  { id:'kule-okcu', baslik:'Okçu Kulesi', kategori:'bina', ikon:'🗼',
    ozet:'Okçu sanal birim — savunmaya ekstra saldırı.',
    stats:{ ATK:50, Tur:'1-3' },
    baglantilar:[{id:'okcu',tip:'ilgili'},{id:'savas-motor',tip:'ilgili'},{id:'surlar',tip:'ilgili'}]},
  { id:'istihbarat', baslik:'İstihbarat Binası', kategori:'bina', ikon:'🏛️',
    ozet:'Casus üretim merkezi.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'casus-incele',tip:'ornek'},{id:'casus-sistem',tip:'ilgili'},{id:'gizlilik',tip:'ilgili'}]},
  { id:'meydan', baslik:'Şehir Meydanı', kategori:'bina', ikon:'🏛️',
    ozet:'Şehir morali pasif bonus +30.',
    baglantilar:[{id:'gps',tip:'ilgili'},{id:'nufus',tip:'ilgili'},{id:'sehir-moral',tip:'saglar'}]},
  { id:'taverna', baslik:'Taverna', kategori:'bina', ikon:'🍺',
    ozet:'Şehir morali +40 pasif bonus.',
    baglantilar:[{id:'festival',tip:'ilgili'},{id:'gps',tip:'ilgili'},{id:'nufus',tip:'ilgili'},{id:'sehir-moral',tip:'saglar'}]},
  { id:'akademi', baslik:'Akademi', kategori:'bina', ikon:'📚',
    ozet:'GPS Eğitim alanı — 5000 nüfus kapsamı.',
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'buyu-sistem',tip:'ilgili'},{id:'gps',tip:'saglar'},{id:'isci',tip:'ilgili'},{id:'sehir-moral',tip:'ilgili'}]},
  { id:'katedral', baslik:'Katedral', kategori:'bina', ikon:'⛪',
    ozet:'Şehir binası — moral +60, 5000 kapsam.',
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'bilge',tip:'ilgili'},{id:'gps',tip:'ilgili'},{id:'koylu',tip:'ilgili'},{id:'sehir-moral',tip:'saglar'}]},

  // ═══ KAYNAKLAR (10) ═══
  { id:'altin', baslik:'Altın', kategori:'kaynak', ikon:'🪙',
    ozet:'Evrensel birim.',
    aciklama:'Vergi, ticaret, ganimet, sandık ile kazanılır. Ordu maaşı altınla ödenir; ödenmeyince Ordu Morali -10.',
    baglantilar:[{id:'festival',tip:'ilgili'},{id:'ordu-maas',tip:'ilgili'},{id:'piyade',tip:'ilgili'},{id:'vergi',tip:'gereklilik'},{id:'vergi',tip:'saglar'}]},
  { id:'odun', baslik:'Odun', kategori:'kaynak', ikon:'🌲',
    ozet:'Temel hammadde. Kereste ve bina maliyeti.',
    baglantilar:[{id:'ev',tip:'ilgili'},{id:'kereste',tip:'ilgili'},{id:'koy',tip:'ilgili'},{id:'oduncu',tip:'gereklilik'}]},
  { id:'metal', baslik:'Metal', kategori:'kaynak', ikon:'⚙️',
    ozet:'Ocak madeni. İşlenmiş metal için kaynak.',
    baglantilar:[{id:'isleme',tip:'ilgili'},{id:'islenmis',tip:'ilgili'},{id:'islenmis',tip:'sonra'},{id:'kolcu',tip:'ilgili'},{id:'ocak',tip:'gereklilik'}]},
  { id:'bugday', baslik:'Buğday', kategori:'kaynak', ikon:'🌾',
    ozet:'Yemek temeli. Tarla → Fırın → Ekmek.',
    baglantilar:[{id:'firin',tip:'ilgili'},{id:'firin',tip:'ilgili'},{id:'koylu',tip:'ilgili'},{id:'tarla',tip:'gereklilik'}]},
  { id:'balik', baslik:'Balık', kategori:'kaynak', ikon:'🐟',
    ozet:'İkinci yemek kaynağı.', baglantilar:[{id:'balikci',tip:'gereklilik'},{id:'bugday',tip:'karsilastir'},{id:'firin',tip:'ilgili'}]},
  { id:'kereste', baslik:'Kereste', kategori:'kaynak', ikon:'🪵',
    ozet:'İşlenmiş odun. Yüksek seviye bina için.',
    baglantilar:[{id:'ev',tip:'ilgili'},{id:'kasaba',tip:'ilgili'},{id:'odun',tip:'gereklilik'}]},
  { id:'islenmis', baslik:'İşlenmiş Metal', kategori:'kaynak', ikon:'🔩',
    ozet:'Yüksek seviye bina + birim maliyeti.',
    baglantilar:[{id:'isin-savasci',tip:'ilgili'},{id:'isleme',tip:'gereklilik'},{id:'metal',tip:'gereklilik'},{id:'paladin',tip:'ilgili'}]},
  { id:'at', baslik:'At', kategori:'kaynak', ikon:'🐎',
    ozet:'Süvari temel bileşeni. Ahır üretir. 1 at = 50 çiğ et (manuel kesim).',
    baglantilar:[{id:'ahir',tip:'gereklilik'},{id:'kadim',tip:'ilgili'},{id:'sovalye',tip:'ilgili'},{id:'suvari',tip:'ilgili'}]},
  { id:'kurt', baslik:'Kurt', kategori:'kaynak', ikon:'🐺',
    ozet:'Kötü taraf süvari atı yerine kurt.',
    baglantilar:[{id:'ahir',tip:'gereklilik'},{id:'at',tip:'karsilastir'},{id:'sovalye',tip:'karsilastir'}]},
  { id:'asker', baslik:'Asker (Ham)', kategori:'kaynak', ikon:'🎖️',
    ozet:'Ünite eğitimi için ham nüfus.',
    aciklama:'Köylülerden dönüştürülür. Geri köylüye çevrilebilir.',
    baglantilar:[{id:'koylu',tip:'gereklilik'},{id:'nufus',tip:'ilgili'},{id:'okcu',tip:'ilgili'},{id:'piyade',tip:'ilgili'},{id:'sovalye',tip:'ilgili'}]},
  { id:'koylu', baslik:'Köylü', kategori:'kaynak', ikon:'👨‍🌾',
    ozet:'Temel nufus birimi. Vergi öder.',
    aciklama:'Asker/işçi/worshipper\'a dönüştürülebilir. Worshipper tek yön (geri dönüşüm yok).',
    baglantilar:[{id:'asker',tip:'sonra'},{id:'ev',tip:'ilgili'},{id:'isci',tip:'sonra'},{id:'nufus',tip:'ilgili'},{id:'vergi',tip:'saglar'}]},
  { id:'isci', baslik:'İşçi', kategori:'kaynak', ikon:'⛏️',
    ozet:'5 tip: oduncu, madenci, çiftçi, balıkçı, tüccar.',
    baglantilar:[{id:'balikci',tip:'ilgili'},{id:'koylu',tip:'gereklilik'},{id:'ocak',tip:'ilgili'},{id:'oduncu',tip:'ilgili'},{id:'tarla',tip:'ilgili'}]},
  { id:'mana-beyaz', baslik:'Beyaz Mana', kategori:'kaynak', ikon:'⚪',
    ozet:'İyileşme & buff büyüleri.',
    baglantilar:[{id:'buyu-sistem',tip:'ilgili'},{id:'buyucu',tip:'ilgili'},{id:'buyucu-kulesi',tip:'ilgili'},{id:'tapinak-rathe',tip:'gereklilik'}]},
  { id:'mana-kirmizi', baslik:'Kırmızı Mana', kategori:'kaynak', ikon:'🔴',
    ozet:'Ateş & saldırı büyüleri.',
    baglantilar:[{id:'buyu-mistik-atak',tip:'ilgili'},{id:'buyu-sistem',tip:'ilgili'},{id:'tapinak-fennin',tip:'gereklilik'}]},
  { id:'mana-mavi', baslik:'Mavi Mana', kategori:'kaynak', ikon:'🔵',
    ozet:'Buz & soğuk büyüleri.',
    baglantilar:[{id:'buyu-sistem',tip:'ilgili'},{id:'mana-beyaz',tip:'karsilastir'},{id:'tapinak-xegony',tip:'gereklilik'}]},
  { id:'mana-yesil', baslik:'Yeşil Mana', kategori:'kaynak', ikon:'🟢',
    ozet:'Doğa & üretim büyüleri.',
    baglantilar:[{id:'buyu-sistem',tip:'ilgili'},{id:'buyulu-tarla',tip:'ilgili'},{id:'tapinak-tunare',tip:'gereklilik'}]},
  { id:'gizlilik', baslik:'Gizlilik', kategori:'kaynak', ikon:'🎭',
    ozet:'Lonca üretir. Casus operasyonu ekonomisi.',
    baglantilar:[{id:'casus-sistem',tip:'ilgili'},{id:'casus-sistem',tip:'saglar'},{id:'kadim',tip:'ilgili'},{id:'lonca',tip:'gereklilik'}]},
  { id:'buyulu-yumurta', baslik:'Büyülü Yumurta', kategori:'kaynak', ikon:'🥚',
    ozet:'Büyülü tarla üretir. Ejderha için.',
    baglantilar:[{id:'buyulu-tarla',tip:'gereklilik'},{id:'ejderha',tip:'saglar'},{id:'magara',tip:'gereklilik'}]},
  { id:'nufus', baslik:'Nüfus', kategori:'kaynak', ikon:'👥',
    ozet:'Ev/Köy/Kasaba kapasitesi. Tek doğruluk kaynağı: /api/game/nufus',
    aciklama:'4 tip: Köylü · Asker · İşçi · Worshipper. Workers.total + Unite toplamı = nüfus.',
    baglantilar:[{id:'asker',tip:'ornek'},{id:'ev',tip:'gereklilik'},{id:'isci',tip:'ornek'},{id:'kasaba',tip:'gereklilik'},{id:'koy',tip:'gereklilik'},{id:'koylu',tip:'ornek'}]},

  // ═══ SAVAS (5) ═══
  { id:'savas-motor', baslik:'6 Turlu Savaş Motoru', kategori:'savas', ikon:'⚔️',
    ozet:'Noxara\'nın kalbi — 6 tur, 4 saf, determined akış.',
    stats:{ Tur:6, Saf:4, Max_Saf_Uye:'∞' },
    quote:'Savaş bir dans değildir — ama ritim sahiptir. Altı tur, dört saf.',
    aciklama:'Savaş Motoru, Noxara\'nın en karmaşık sistemi. Altı tur boyunca iki ordu birbiriyle çarpışır; her tur saflar sırayla saldırır.\n\nHer ünite tipi savaş turlarında sadece belirli turlarda saldırır (Okçu 1-3, Piyade 4-6 gibi). Her tur hangi safın saldırıda olduğu da sabit. Bu nedenle düzelme = her şey.',
    detay:'**Tur Sırası**:\n- Tur 1-2: Saf 1 saldırır\n- Tur 3: Saf 1 + Saf 2\n- Tur 4: Saf 1 + Saf 2 + Saf 3\n- Tur 5-6: Tüm saflar (4 dahil)\n\n**Hasar Akışı**:\n1. Her saldıran ünite `atk × adet × iskaCarpan` verir\n2. Gelen hasar hedef safındaki ünitelere `kalanDef` oranla dağıtılır\n3. Her ünite kendi zırhıyla azaltma uygular\n4. Arta kalan hasar ünite canından düşer\n\n**Kazanan**: 6 tur sonunda ordu yok olduysa olmayan taraf kaybeder. İki taraf da ayaktaysa kalan DEF bazında galibiyet.\n\n**1. Çağ Koruma**: Savunan oyuncu çağ < 2 ise saldırılamaz.',
    strateji:[
      'Okçu\'nu saf 1\'e asla koyma — ilk turda hasar veremeyecek menzilli birim, hemen ölür.',
      'Saf 1 sayı çokluğu, saf 4 elit birim. Düşmanın eriyişini izle.',
      'Karma ordu > saf ordu. 100 piyade < 80 piyade + 20 okçu + 10 paladin.',
      'Savunmada kale bonusu %20 zırh — surları kur.'
    ],
    ipucu:'İlk savaşlarında simülatörü kullan — premium ücret öder ama birkaç test = bin altın ganimet.',
    dikkat:'Savaş geri alınamaz. İptal edince ordu döner ama kayıplar geri gelmez.',
    baglantilar:[{id:'savas-saf',tip:'ilgili'},{id:'zirh-iska',tip:'ilgili'},{id:'ordu-moral',tip:'ilgili'},{id:'kale-bonus',tip:'ilgili'}]},
  { id:'savas-saf', baslik:'Saf Dizilimi (4 saf)', kategori:'savas', ikon:'🪖',
    ozet:'Hangi birim hangi safta? = strateji.',
    aciklama:'Her tipten 1 birim 1 safa. Adet farketmez. Saf 1 ön hat, Saf 4 korumalı.',
    baglantilar:[{id:'savas-motor',tip:'ilgili'},{id:'piyade',tip:'ornek'},{id:'okcu',tip:'ornek'}]},
  { id:'zirh-iska', baslik:'Zırh & İska (v1.14.0.45)', kategori:'savas', ikon:'🛡️',
    ozet:'Birim bazlı — her ünite kendi zırhıyla hasar emer.',
    stats:{ Azaltma:'Zirh/50', İskaMod:'(1-iska/100)', Cap:'yok (asimptot)' },
    quote:'Eski günlerde zırh havuzdu — paladinler piyadenin yanında erirdi.',
    aciklama:'v1.14.0.45\'e kadar zırh havuz halindeydi — tüm saftaki ünitelerin ortalaması gelen hasarı azaltırdı. Bu sovalye ve paladin gibi yüksek zırhlı birimlerin katkısını boşa çıkarırdı.\n\nYeni sistemde her birim kendi zırhıyla emer. Paladin (zırh 35), piyade (20) yanındayken artık üç katı dayanıklılık gösterir.',
    detay:'**Yeni Formül (Albion tarzı)**:\n`unitHasar = rawHasar / (1 + zirh/50)`\n\nDoğal diminishing returns: zirh arttıkça azalma fazla olur ama asla %100 olmaz.\n\n**Azaltma Tablosu**:\n- Zirh 0 → %0 azaltma\n- Zirh 20 (piyade) → %29\n- Zirh 25 (savaşçı, okcu kulesi) → %33\n- Zirh 35 (paladin) → %41\n- Zirh 40 (ışığın savaşçısı) → %44\n- Zirh 70 (ejderha) → %58\n- Zirh 75 (altın ejderha) → %60\n\n**İska (v1.14.0.45)**: Eskiden "all-or-nothing" random (%20 iska = %20 ihtimalle TUM atak 0). Şimdi deterministik: `atk × (1 - iska/100)`. 100 okcu × iska 20 → her zaman 80 okcu hasarı verir.\n\n**Simülatör**: Tutarlı — aynı setup her çalıştırmada aynı sonucu verir.',
    strateji:[
      'Yüksek zırhlı birimi ön safa koy — gerçekten tanklık yapar.',
      'Kale bonusu +%20 zırh — savunmada mutlaka surları kur.',
      'Elit birim karışımı: 1 paladin 3 piyadeden daha dayanıklı (ama pahalı).'
    ],
    ipucu:'v1.14.0.45 öncesi savaş loglarını tekrar okursan, o savaşlar yeni sistemle aynı sonucu vermez. Yeni simülatör sonuçlarına güven.',
    baglantilar:[{id:'savas-motor',tip:'ilgili'},{id:'paladin',tip:'ornek'},{id:'piyade',tip:'ornek'},{id:'ejderha',tip:'ornek'}]},
  { id:'kale-bonus', baslik:'Kale Bonusu', kategori:'savas', ikon:'🏰',
    ozet:'Savunan tarafın tüm zırhları +%20.',
    baglantilar:[{id:'surlar',tip:'gereklilik'},{id:'savas-motor',tip:'ilgili'}]},
  { id:'ordu-maas', baslik:'Ordu Maaşı', kategori:'savas', ikon:'💸',
    ozet:'Her saat ödenir. Maaş yoksa → Ordu Morali -10.',
    baglantilar:[{id:'altin',tip:'gereklilik'},{id:'ordu-moral',tip:'ilgili'}]},

  // ═══ BUYU (7) ═══
  { id:'buyu-sistem', baslik:'Büyü Sistemi (28 büyü)', kategori:'buyu', ikon:'🔮',
    ozet:'10 kademe, 4 renk mana, 5 çağ.',
    stats:{ Büyü:28, Kademe:10, Renk:4 },
    aciklama:'Mistik Atak, Motivasyon, Ejderha Sevinci, Hipnoz, Sadakat, Yakarış... Mana maliyeti v1.13.70.2 ile ×10.',
    baglantilar:[{id:'buyucu-kulesi',tip:'gereklilik'},{id:'mana-beyaz',tip:'gereklilik'},{id:'bilge',tip:'ilgili'}]},
  { id:'buyu-mistik-atak', baslik:'Mistik Atak', kategori:'buyu', ikon:'💥',
    ozet:'Savaşta saldırı birimlerin ATK +3, DEF -6.',
    aciklama:'Savaş simülatöründe +3/-6 offset. Karmaşık.',
    baglantilar:[{id:'buyu-sistem',tip:'ilgili'},{id:'savas-motor',tip:'ilgili'}]},
  { id:'buyu-ejderha-sevinci', baslik:'Ejderha Sevinci', kategori:'buyu', ikon:'🐲',
    ozet:'Kendine atılır. Şehir morali +X, 6h cooldown.',
    aciklama:'SADECE şehir moralini artırır. Ordu moraline HİÇBİR etkisi yok.',
    baglantilar:[{id:'sehir-moral',tip:'saglar'}]},
  { id:'buyu-motivasyon', baslik:'Motivasyon', kategori:'buyu', ikon:'💪',
    ozet:'Buff — ordu morali artırır (müttefike).',
    baglantilar:[{id:'ordu-moral',tip:'saglar'}]},
  { id:'buyu-hipnoz', baslik:'Hipnoz', kategori:'buyu', ikon:'🌀',
    ozet:'Hedef ordusunun moralini düşürür.',
    baglantilar:[{id:'ordu-moral',tip:'ilgili'}]},
  { id:'bilge', baslik:'Bilge Sistemi', kategori:'buyu', ikon:'🧙',
    ozet:'4 bilge, 336 PG\'de dünya bilgesi değişir.',
    aciklama:'Her 168 PG seçim. Bilge 2× mana verir. Cooldown global.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'tapinak-rathe',tip:'ilgili'},{id:'buyu-sistem',tip:'ilgili'}]},
  { id:'parsomen', baslik:'Parşömen', kategori:'buyu', ikon:'📜',
    ozet:'Okuyarak yeni büyü öğrenmenin yolu.',
    aciklama:'Sandık, Büyü Dükkanı veya savaş ganimetinden çıkar. Büyücü kulesinde okunur.',
    baglantilar:[{id:'buyucu-kulesi',tip:'ilgili'}]},

  // ═══ CASUS (3) ═══
  { id:'casus-sistem', baslik:'Casus Sistemi (11 operasyon)', kategori:'casus', ikon:'🕵️',
    ozet:'İstihbarattan eğitilir. 11 görev tipi.',
    aciklama:'İncele, Hırsızlık, Kargaşa, Katliam, Sabotaj, Parşömen Çal... Can + deneyim + ölüm.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'istihbarat',tip:'gereklilik'},{id:'gizlilik',tip:'gereklilik'}]},
  { id:'casus-incele', baslik:'İncele (Casus)', kategori:'casus', ikon:'🔍',
    ozet:'Hedef krallığın kaynak/ordu/bina bilgisi.',
    baglantilar:[{id:'casus-sistem',tip:'ilgili'}]},
  { id:'casus-sabotaj', baslik:'Sabotaj (Casus)', kategori:'casus', ikon:'💥',
    ozet:'Hedef binasına %X hasar verir.',
    baglantilar:[{id:'casus-sistem',tip:'ilgili'}]},

  // ═══ CAG (5) ═══
  { id:'cag', baslik:'5 Çağ Sistemi', kategori:'cag', ikon:'⏳',
    ozet:'Sonatas → Heonteas → Kronitas → Rashnotor → Noxara',
    aciklama:'1 PG = 1 gerçek saat. Her çağ yeni binalar/birimler/büyüler.',
    baglantilar:[{id:'cag1',tip:'ornek'},{id:'cag2',tip:'ornek'}]},
  { id:'cag1', baslik:'I. Çağ — Sonatas', kategori:'cag', ikon:'🌅',
    ozet:'Başlangıç çağı. Temel ekonomi.',
    aciklama:'Koruma: savunan çağ < 2 ise saldırılamaz.',
    baglantilar:[{id:'cag',tip:'ilgili'},{id:'piyade',tip:'ornek'}]},
  { id:'cag2', baslik:'II. Çağ — Heonteas', kategori:'cag', ikon:'🏹',
    ozet:'Askeri açılım. Ahir, Tapınak, İstihbarat.',
    baglantilar:[{id:'cag',tip:'ilgili'},{id:'sovalye',tip:'ornek'}]},
  { id:'cag3', baslik:'III. Çağ — Kronitas', kategori:'cag', ikon:'🔮',
    ozet:'Büyü + Guild açılımı.',
    baglantilar:[{id:'cag',tip:'ilgili'},{id:'buyulu-tarla',tip:'ornek'},{id:'guild',tip:'ornek'}]},
  { id:'cag4', baslik:'IV. Çağ — Rashnotor', kategori:'cag', ikon:'⚔️',
    ozet:'Elit birimler + Ejderha.',
    baglantilar:[{id:'cag',tip:'ilgili'},{id:'ejderha',tip:'ornek'}]},
  { id:'cag5', baslik:'V. Çağ — Noxara', kategori:'cag', ikon:'🌑',
    ozet:'Usta seviye. Kusatma + sezon sonu.',
    baglantilar:[{id:'cag',tip:'ilgili'}]},

  // ═══ MORAL (4) ═══
  { id:'sehir-moral', baslik:'Şehir Morali 🏛️', kategori:'moral', ikon:'😊',
    ozet:'Halkın memnuniyeti. 0-5000 skalası. Vergi ile ilgilidir.',
    stats:{ Max_Cag1:1500, Max_Cag5:5000, Min:-1500, Varsayılan:500 },
    quote:'Kral altın toplar, halk sabır tüketir.',
    aciklama:'Şehir Morali halkının sana olan inancını ölçer. Yüksekse işçiler mutlu çalışır, köylüler doğar. Düşerse köylüler kaçar, işçi üretimi düşer, ekonomi çöker.\n\n**Bu ORDU MORALİ DEĞİLDİR** — iki sistem tamamen ayrı. Şehir morali vergi, yiyecek, festival ile ilgili; Ordu morali maaş ile ilgili.',
    detay:'**Artıranlar**:\n- Festival (+200 / +500 / +1500 seviyeye göre)\n- Ejderha Sevinci büyüsü (+X, 6h cooldown)\n- Bina pasif bonusları (Lonca +50, Tapinak +25/adet, Meydan +30, Taverna +40, Noxara Hani +50, Muze +80, Asma Bahceler +100)\n- 5 İlgi Alanı GPS kapsama (bkz. GPS node)\n- Yemek çeşitliliği (3+ tür +1-2/saat)\n- Pasif GPS ≥ %90 → +4-6 moral/saat\n\n**Düşüren**:\n- Vergi oranı (0→0 ceza, 5→-18, 10→-90, 15→-210, 20→-380, 25→-600/saat)\n- Açlık (doyma <%50 → -3, <%70 → -1)\n- Savaş kaybı (-15)\n\n**Sonuçları**:\n- Düşük moral → işçi üretim çarpanı düşük\n- Çok düşük moral → köylü kaçışı başlar\n- Negatif moral → ciddi ekonomik kriz',
    strateji:[
      'Vergiyi 5\'in üstüne çıkarma — moral cezası geri kazanılmaz.',
      'Lonca + 4 Tapınak + Meydan + Taverna = sabit +200 pasif moral.',
      'GPS %90\'ı geç — pasif +4 moral/saat büyük farktır.',
      'Festival nadir ama güçlü — kritik savaş öncesi kraliyet festivali at.'
    ],
    ipucu:'Yeni oyuncuda vergiyi 0 tut. Hazine birikince yavaşça 2-3\'e çık. 5+ sadece premium oyuncuları güven duymalı.',
    dikkat:'ŞEHİR MORALİ ve ORDU MORALİ iki ayrı sistem. Şehir moralinin düşmesi, askerlerinin zayıflaması demek DEĞİLDİR.',
    baglantilar:[{id:'vergi',tip:'ilgili'},{id:'gps',tip:'ilgili'},{id:'festival',tip:'ilgili'},{id:'ordu-moral',tip:'karsilastir'},{id:'buyu-ejderha-sevinci',tip:'saglar'}]},

  { id:'ordu-moral', baslik:'Ordu Morali ⚔️', kategori:'moral', ikon:'🎖️',
    ozet:'Askerin savaş gücü. 0-100 skalası. Maaş ile ilgilidir.',
    stats:{ Max:100, Min:0, Varsayılan:100 },
    quote:'Maaşsız asker silah bırakır, hipnozlu asker düşmana koşar.',
    aciklama:'Ordu Morali askerlerinin savaşta ne kadar sert çarpışacağını ölçer. ATK ve DEF çarpanı olarak uygulanır: `gerçekATK = baseATK × moral/100`.\n\n**Bu ŞEHİR MORALİ DEĞİLDİR** — halkın memnuniyetiyle karıştırma.',
    detay:'**Artıranlar**:\n- Maaş ödemesi +5 (her saat ödendiğinde)\n- Sadakat büyüsü (kendine atılır)\n\n**Düşüren**:\n- Maaş ödenmemesi -10 (altın yoksa)\n- Hipnoz büyüsü (düşmanın üstüne)\n\n**Formül (v1.14.0.45)**:\n`ATK/DEF carpan = max(0.2, moral/100)`\n\nMoral 100 = tam güç, moral 50 = yarım güç, moral 0 = **%20** (min 0.2). Ordu moralsiz kalsa bile tamamen etkisiz olmaz.\n\n**Not**: Ordun yoksa ordu morali irrelevant. Maaş ödüyorsan %100\'de kalır (nadiren hipnoz yersen geçici düşer).',
    strateji:[
      'Savaştan önce maaş ödeyebildiğinden emin ol — %100 moral vs %80 moral = %25 fark.',
      'Hipnoz yersen Sadakat büyüsüyle kendi moralini onar.',
      'Moralin düşükken saldırma — zayıf hasar verirsin, zayıf DEF gösterirsin.'
    ],
    ipucu:'Maaş kesildiğinde 1 saat içinde altın tedarik et — moral -10 birikirse toparlanması yıllar sürer.',
    dikkat:'Şehir Moralinin düşmesi ORDU MORALİNE etki etmez. Bunu karıştıran oyuncu stratejik hata yapar.',
    baglantilar:[{id:'ordu-maas',tip:'ilgili'},{id:'sehir-moral',tip:'karsilastir'},{id:'savas-motor',tip:'ilgili'},{id:'buyu-hipnoz',tip:'ilgili'}]},
  { id:'gps', baslik:'GPS (5 İlgi Alanı)', kategori:'moral', ikon:'📊',
    ozet:'Populasyon Seviyesi.',
    aciklama:'5 alan: Eğitim/Bilgi/Kültür/Eğlence/Şehir. Ortalama kapsama %. GPS ≥ %90 → +4 moral/saat.',
    baglantilar:[{id:'sehir-moral',tip:'ilgili'}]},
  { id:'vergi', baslik:'Vergi Sistemi (5 plug-in)', kategori:'moral', ikon:'💰',
    ozet:'Admin seçer: Klasik/GPS/Progressive/Dinamik/Premium.',
    aciklama:'Vergi oranı yüksek → şehir morali düşer. Cezalar katlanarak artar.',
    baglantilar:[{id:'altin',tip:'saglar'},{id:'sehir-moral',tip:'ilgili'}]},
  { id:'festival', baslik:'Festival', kategori:'moral', ikon:'🎉',
    ozet:'Altın + ekmek → şehir morali +X.',
    aciklama:'3 seviye: Küçük/Büyük/Kraliyet. Eski Palantis: +200/+500/+1500.',
    baglantilar:[{id:'sehir-moral',tip:'saglar'}]},

  // ═══ GUILD (4) ═══
  { id:'guild', baslik:'Guild Sistemi', kategori:'guild', ikon:'🏰',
    ozet:'Oyuncu toplulukları. Ortak şehir + ordu.',
    aciklama:'Guild taraf kilitli (v1.14.0.44). Faz 1: üyelik. Faz 2: bina/ordu. Faz 3: Kadim kuşatma.',
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'diplomasi',tip:'ilgili'},{id:'tech-tree',tip:'ilgili'},{id:'kadim',tip:'ilgili'}]},
  { id:'diplomasi', baslik:'Diplomasi (v1.14.0.30)', kategori:'guild', ikon:'🤝',
    ozet:'4 durum: BARIŞ / ANTLAŞMA / SAVAŞ / TABİYET.',
    aciklama:'İhanet debuff: savaşta -%6 ATK/DEF. Tabiyet: bağlı üretiminin %30\'u Hakim\'e.',
    baglantilar:[{id:'guild',tip:'ilgili'}]},
  { id:'tech-tree', baslik:'Guild Tech Tree', kategori:'guild', ikon:'🔬',
    ozet:'5 teknoloji — üretim/savunma/atk/inşaat/ekonomi.',
    baglantilar:[{id:'guild',tip:'ilgili'}]},
  { id:'kusatma', baslik:'Kadim Kuşatma', kategori:'guild', ikon:'⚔️',
    ozet:'Guild ortak saldırı — kadim şehir ele geçirme.',
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'kadim',tip:'ilgili'},{id:'guild',tip:'gereklilik'}]},

  // ═══ KADIM (3) ═══
  { id:'kadim', baslik:'Kadim Şehirler', kategori:'kadim', ikon:'🏺',
    ozet:'Aurium (Işık) + Gorathul (Karanlık). Antik medeniyetler.',
    stats:{ Sehir:2, Geri_Sayim:'240 PG', Varis:'3 PG', Butce_Carpan:'2.0x' },
    quote:'Aurium ve Gorathul binlerce yıl evveldi. Mananın, atın, gizliliğin anası onlardır.',
    aciklama:'Aurium ve Gorathul, Noxara evrenin en eski medeniyetleridir — binlerce yıl önceki antik krallıklar. Genç krallar (oyuncular) mananın, atın, ejderha yumurtasının bilgisini onların mirasından öğrendi.\n\n**Aurium** (X=15, Y=8) Işık tarafı; **Gorathul** (X=185, Y=42) Karanlık tarafı. Her ikisiyle de ticaret yapabilirsin — ama dikkat.',
    detay:'**Ticaret Dansı (240 PG geri sayım)**:\n1. **İlk ticaret**: Bir şehrin stokundan satın al → `ilk_ticaret_at = NOW()`\n2. **240 PG pencere**: Bu süre boyunca yaptığın her ticaret toplanır (`pencere_ticaret`)\n3. **Çapraz hareket**: 240 PG dolunca **karşı şehir** sana saldırır (Aurium\'dan alan Gorathul\'dan saldırı alır)\n4. **3 PG yolculuk**: Ordu hareket eder, sabit 3 PG içinde varır (konumun fark etmez)\n5. **24 PG uyarı**: Saldırıdan 24 PG önce bildirim + Telegram mesajı\n6. **Saldırı bütçesi**: `pencere_ticaret × 2.0 altın` değerinde NPC ordusu\n7. **Reset**: Saldırıdan sonra sayaç sıfırlanır, yeni döngü başlar\n\n**NPC Ordusu (v1.14.0.12)**:\n- Oyuncu birimleri aynen kullanılır (piyade, paladin, ejderha vs.)\n- **TÜM GELIŞIMLER MAX** (atk_sev=10, def_sev=10) — binlerce yılın birikimi\n- NPC morali her zaman %100\n- Çağ filtresi: senin çağına uygun birimler (1. Çağ oyuncuya ejderha gitmez)\n\n**Kadim Şehir Savunma Bütçesi**: Guild kuşatması sırasında, şehrin ordusu `toplam_yapilan_ticaret × 2.0 / 100` altın değerinde.',
    strateji:[
      'Ticaret büyük ödül, büyük risk. Az miktarda al → düşük saldırı bütçesi.',
      'Farklı şehirlerden değişimli al — bir şehirle uzun pencere açma.',
      'Saldırı uyarısı geldiğinde (24 PG kala) orduyu ve kuleleri kontrol et.',
      'Bol altınla birikmiş savunma (200K+) savunma yerine temel bina güvenliği sağlar.'
    ],
    ipucu:'İlk ticareti 3. çağa kadar bekle — alacağın saldırı elit birim içerir, düşük çağda karşılayamazsın.',
    dikkat:'240 PG çok uzun (10 gün!) görünür ama hızlı geçer. Ticaret geçmişini unutma — sayaç arka planda dolar.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'at',tip:'saglar'},{id:'mana-beyaz',tip:'saglar'},{id:'gizlilik',tip:'saglar'},{id:'aurium',tip:'ornek'},{id:'gorathul',tip:'ornek'},{id:'kusatma',tip:'ilgili'}]},
  { id:'aurium', baslik:'Aurium', kategori:'kadim', ikon:'☀️',
    ozet:'Işık kadim şehri. X=15 Y=8.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'kadim',tip:'ilgili'}]},
  { id:'gorathul', baslik:'Gorathul', kategori:'kadim', ikon:'🌑',
    ozet:'Karanlık kadim şehri. X=185 Y=42.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'kadim',tip:'ilgili'}]},

  // ═══ IRKLAR (9 — genel + 8) ═══
  { id:'irk', baslik:'8 Irk (İyi / Kötü)', kategori:'irk', ikon:'👑',
    ozet:'İnsan/Elf/Cüce/Bucukluk × Kara Elf/Ork/Ogre/Undead',
    aciklama:'Taraf kilitli. ATK/DEF/kaynak bonusu. Paladin iyi, Kara Şövalye kötü.',
    baglantilar:[{id:'insan',tip:'ornek'},{id:'kara-elf',tip:'ornek'}]},
  { id:'insan', baslik:'İnsan', kategori:'irk', ikon:'👑',
    ozet:'Dengeli ırk. Her alanda hafif bonus.',
    stats:{ ATK:'+2', DEF:'+2', Altın:'+2%', Odun:'+2%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'elf', baslik:'Elf', kategori:'irk', ikon:'🌿',
    ozet:'Doğa ve büyü ustası.',
    stats:{ Odun:'+5%', Mana:'+5%', ATK:'+5' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'cuce', baslik:'Cüce', kategori:'irk', ikon:'⚒️',
    ozet:'Madenci ve zanaatkar.',
    stats:{ Metal:'+5%', DEF:'+5', BinaFiyat:'-10%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'bucukluk', baslik:'Bucukluk', kategori:'irk', ikon:'🎭',
    ozet:'Kurnaz tüccar. Casusluk uzmanı.',
    stats:{ Altın:'+7%', Gizlilik:'+5%', CasusBaşarı:'+5%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'kara-elf', baslik:'Kara Elf', kategori:'irk', ikon:'🖤',
    ozet:'Karanlık büyü ve zehir.',
    stats:{ Gizlilik:'+8%', ZehirATK:'+10%', Mana:'+5%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'ork', baslik:'Ork', kategori:'irk', ikon:'💪',
    ozet:'Ham güç ve savaş.',
    stats:{ ATK:'+8', Metal:'+5%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'ogre', baslik:'Ogre', kategori:'irk', ikon:'👹',
    ozet:'Dev güç, yavaş, yıkıcı.',
    stats:{ ATK:'+10', DEF:'+5', BinaYıkım:'+15%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'undead', baslik:'Undead', kategori:'irk', ikon:'💀',
    ozet:'Ölümsüz, soğuk.',
    stats:{ ATK:'+8', DEF:'+8' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
];

window.CODEX_BAG_LABEL = {
  gereklilik: { label:'Gereklilik',  ikon:'⬅',  renk:'#e74c3c' },
  saglar:     { label:'Sağlar',      ikon:'➜',  renk:'#2ecc71' },
  ilgili:     { label:'İlgili',      ikon:'◌',  renk:'#3498db' },
  karsilastir:{ label:'Karşılaştır', ikon:'⚖',  renk:'#d4a257' },
  sonra:      { label:'Sonrası',     ikon:'→',  renk:'#9b59b6' },
  ornek:      { label:'Örnek',       ikon:'◆',  renk:'#1abc9c' },
  'ornek-kilit':{label:'Örnek (Kilitli)', ikon:'◆', renk:'#95a5a6' },
};

// Global helper — node id'den obje bul
window.codexGetNode = function(id) {
  return window.CODEX_NODES.find(n => n.id === id);
};
