/* ═══════════════════════════════════════════════════════
   NOXARA CODEX — Merkezi veri (codex.html + palette + tooltip)
   v1.14.0.54 — 60+ node, 11 kategori
═══════════════════════════════════════════════════════ */
window.CODEX_KATEGORILER = [
  { id:'unite',  isim:'Üniteler',  ikon:'⚔️', renk:'#e74c3c' },
  { id:'bina',   isim:'Binalar',   ikon:'🏛️', renk:'#c9a84c' },
  { id:'kaynak', isim:'Kaynaklar', ikon:'💎', renk:'#3498db' },
  { id:'savas',  isim:'Savaş',     ikon:'🛡️', renk:'#9b59b6' },
  { id:'buyu',   isim:'Büyüler',   ikon:'🔮', renk:'#8e44ad' },
  { id:'casus',  isim:'Casus',     ikon:'🕵️', renk:'#2ecc71' },
  { id:'cag',    isim:'Çağ',       ikon:'⏳', renk:'#f39c12' },
  { id:'moral',  isim:'Moral',     ikon:'😊', renk:'#1abc9c' },
  { id:'guild',  isim:'Guild',     ikon:'🏰', renk:'#16a085' },
  { id:'kadim',  isim:'Kadim',     ikon:'🏺', renk:'#d4af37' },
  { id:'irk',    isim:'Irklar',    ikon:'👑', renk:'#e67e22' },
];

window.CODEX_NODES = [
  // ═══ UNITELER (11) ═══
  { id:'piyade', baslik:'Piyade', kategori:'unite', tier:'T1', ikon:'🗡️',
    ozet:'Hafif piyade. Her krallığın ilk savaş birimi.',
    stats:{ ATK:2, DEF:10, Zirh:20, İska:10, Maaş:20, Tur:'4-6' },
    aciklama:'Saf 1 veya 2\'ye yerleştirilir. Zirhı orta, hasarı düşük ama ucuz ve hızlı eğitilir.',
    baglantilar:[{id:'asker',tip:'gereklilik'},{id:'altin',tip:'gereklilik'},{id:'savas-saf',tip:'ilgili'},{id:'okcu',tip:'karsilastir'},{id:'sovalye',tip:'karsilastir'}]},
  { id:'okcu', baslik:'Okçu', kategori:'unite', tier:'T1', ikon:'🏹',
    ozet:'Menzilli birim. Arka saftan ateş eder.',
    stats:{ ATK:5, DEF:12, Zirh:10, İska:20, Maaş:28, Tur:'1-3' },
    aciklama:'İlk 3 turda saldırır (menzilli). Okçu kuleleri savunmaya ekstra destek.',
    baglantilar:[{id:'asker',tip:'gereklilik'},{id:'zirh-iska',tip:'ilgili'},{id:'piyade',tip:'karsilastir'},{id:'kule-okcu',tip:'ilgili'}]},
  { id:'savasci', baslik:'Savaşçı', kategori:'unite', tier:'T2', ikon:'⚔️',
    ozet:'Orta agirlik. Daha dayanikli piyade.',
    stats:{ ATK:6, DEF:18, Zirh:25, İska:20, Maaş:32 },
    baglantilar:[{id:'piyade',tip:'sonra'},{id:'kolcu',tip:'karsilastir'}]},
  { id:'sovalye', baslik:'Şövalye', kategori:'unite', tier:'T2', ikon:'🐴',
    ozet:'Ağır süvari. Çağ 2+ at gerektirir.',
    stats:{ ATK:6, DEF:22, Zirh:20, İska:15, Maaş:40, Tur:'4-6' },
    aciklama:'1 at + 1 asker + altın = 1 şövalye. Saf 2-3 tercih edilir.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2},ipucu:'2. Çağa geç, ardından Ahır kur'},
    baglantilar:[{id:'at',tip:'gereklilik'},{id:'ahir',tip:'gereklilik'},{id:'piyade',tip:'karsilastir'},{id:'paladin',tip:'sonra'}]},
  { id:'suvari', baslik:'Süvari', kategori:'unite', tier:'T2', ikon:'🏇',
    ozet:'Hizli saldiri birimi.',
    stats:{ ATK:8, DEF:26, Zirh:20, İska:15, Maaş:40 },
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'at',tip:'gereklilik'},{id:'sovalye',tip:'karsilastir'}]},
  { id:'paladin', baslik:'Paladin', kategori:'unite', tier:'T3', ikon:'⚜️',
    ozet:'Elit agır piyade. Kutsal birimler.',
    stats:{ ATK:9, DEF:33, Zirh:35, İska:20, Maaş:52 },
    aciklama:'Yüksek zırh + def. Yeni sistemde her birim kendi zırhıyla hasarı emer → paladin gerçekten tanklık yapar.',
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'sovalye',tip:'karsilastir'},{id:'zirh-iska',tip:'ilgili'},{id:'isin-savasci',tip:'sonra'}]},
  { id:'kolcu', baslik:'Kolcu', kategori:'unite', tier:'T3', ikon:'🗡️',
    ozet:'Elit piyade, savasci sonrasi.',
    stats:{ ATK:10, DEF:30, Zirh:25, İska:20, Maaş:76 },
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'savasci',tip:'sonra'}]},
  { id:'buyucu', baslik:'Büyücü', kategori:'unite', tier:'T3', ikon:'🧙',
    ozet:'Saf 3-4 elit birim, mana kullanir.',
    stats:{ ATK:11, DEF:18, Zirh:20, İska:15, Maaş:120 },
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'mana-beyaz',tip:'gereklilik'},{id:'buyucu-kulesi',tip:'ilgili'}]},
  { id:'isin-savasci', baslik:'Işığın Savaşçısı', kategori:'unite', tier:'T4', ikon:'✨',
    ozet:'Elit iyi taraf savaşçısı.',
    stats:{ ATK:40, DEF:100, Zirh:40, İska:10 },
    aciklama:'Sadece iyi taraf üretebilir. Kötü taraf eşdeğeri: Gölge Savaşçısı.',
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'paladin',tip:'karsilastir'},{id:'golge-savasci',tip:'karsilastir'},{id:'irk',tip:'ilgili'}]},
  { id:'golge-savasci', baslik:'Gölge Savaşçısı', kategori:'unite', tier:'T4', ikon:'🌑',
    ozet:'Elit kotu taraf savasciisi.',
    stats:{ ATK:40, DEF:100, Zirh:40, İska:10 },
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'isin-savasci',tip:'karsilastir'},{id:'irk',tip:'ilgili'}]},
  { id:'ejderha', baslik:'Ejderha (4 tip)', kategori:'unite', tier:'T4', ikon:'🐉',
    ozet:'Nadir uzeri nadir — savas alaninda tanri.',
    stats:{ ATK:'7500-10000', DEF:'2500-5000', Zirh:'70-75', Maaş:250 },
    aciklama:'4 tip: Mavi/Altın (iyi), Kırmızı/Siyah (kötü). Buyulu yumurta + magaradan cıkar. Kadim sehirler ejderha evcilleştirmenin kaynağı.',
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'buyulu-yumurta',tip:'gereklilik'},{id:'magara',tip:'ilgili'},{id:'kadim',tip:'ilgili'}]},

  // ═══ BINALAR (14) ═══
  { id:'ev', baslik:'Ev', kategori:'bina', ikon:'🏠',
    ozet:'10 nüfus kapasitesi.', stats:{ Nüfus:10 },
    baglantilar:[{id:'nufus',tip:'saglar'},{id:'koy',tip:'sonra'}]},
  { id:'koy', baslik:'Köy', kategori:'bina', ikon:'🏘️',
    ozet:'100 nüfus. 20 Köy → 1 Kasaba + 5 doğum bonusu.', stats:{ Nüfus:100 },
    aciklama:'Eski Palantis kuralı: 20 köy birleştirilebilir → kasaba + doğum bonusu.',
    baglantilar:[{id:'ev',tip:'sonra'},{id:'kasaba',tip:'sonra'}]},
  { id:'kasaba', baslik:'Kasaba', kategori:'bina', ikon:'🏯',
    ozet:'2000 nüfus. Büyük yerleşim.', stats:{ Nüfus:2000 },
    baglantilar:[{id:'koy',tip:'sonra'}]},
  { id:'oduncu', baslik:'Oduncu Kampı', kategori:'bina', ikon:'🌲',
    ozet:'Odun üretir. Başlangıç binası.',
    stats:{ Üretim:'10/PG/işçi', Kapasite:'40 oduncu' },
    aciklama:'Yeni oyuncuya 2 oduncu kampı verilir. Her oduncu işçisi saatte 10 odun getirir.',
    baglantilar:[{id:'odun',tip:'saglar'},{id:'isci',tip:'gereklilik'}]},
  { id:'tarla', baslik:'Tarla', kategori:'bina', ikon:'🌾',
    ozet:'Çiftçi kapasitesi + buğday.',
    stats:{ Kapasite:'50 çiftçi/tarla', Üretim:'8/PG/çiftçi' },
    aciklama:'Tarla yoksa çiftçi atanamaz.',
    baglantilar:[{id:'bugday',tip:'saglar'}]},
  { id:'balikci', baslik:'Balıkçı', kategori:'bina', ikon:'🎣',
    ozet:'Balıkçı kapasitesi + balık.',
    aciklama:'Balıkçılar 4-8-12-16-20-24. Palantis günlerinde üretim yapar.',
    baglantilar:[{id:'balik',tip:'saglar'}]},
  { id:'ocak', baslik:'Ocak', kategori:'bina', ikon:'⛰️',
    ozet:'Metal madeni.', baglantilar:[{id:'metal',tip:'saglar'}]},
  { id:'isleme', baslik:'İşleme', kategori:'bina', ikon:'🔨',
    ozet:'Metal → İşlenmiş Metal.',
    baglantilar:[{id:'metal',tip:'gereklilik'},{id:'islenmis',tip:'saglar'}]},
  { id:'firin', baslik:'Fırın', kategori:'bina', ikon:'🥖',
    ozet:'Buğday → Ekmek, Balık → Pişmiş.',
    baglantilar:[{id:'bugday',tip:'gereklilik'}]},
  { id:'ahir', baslik:'Ahır', kategori:'bina', ikon:'🐎',
    ozet:'At ve kurt üretir. Süvari temeli.',
    stats:{ Üretim:'%0.1/saat', Çağ:'≥2' },
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'at',tip:'saglar'},{id:'sovalye',tip:'ilgili'}]},
  { id:'lonca', baslik:'Lonca', kategori:'bina', ikon:'🎭',
    ozet:'Gizlilik üretir. Casus ekonomisi.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'gizlilik',tip:'saglar'}]},
  { id:'buyulu-tarla', baslik:'Büyülü Tarla', kategori:'bina', ikon:'🌱',
    ozet:'Büyülü yumurta — ejderha için.',
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'buyulu-yumurta',tip:'saglar'},{id:'ejderha',tip:'ilgili'}]},
  { id:'magara', baslik:'Mağara', kategori:'bina', ikon:'🕳️',
    ozet:'Nadir ejderha yumurtası.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'ejderha',tip:'ilgili'}]},
  { id:'tapinak-rathe', baslik:'Rathe Tapınağı (Beyaz)', kategori:'bina', ikon:'⛪',
    ozet:'Beyaz worshipper → Beyaz mana.',
    aciklama:'Worshipper geri döndürülemez. Her worshipper 0.1 mana/saat. Bilge 2x verir.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'mana-beyaz',tip:'saglar'},{id:'bilge',tip:'ilgili'}]},
  { id:'tapinak-xegony', baslik:'Xegony Tapınağı (Mavi)', kategori:'bina', ikon:'💠',
    ozet:'Mavi mana — buz/soğuk okulu.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'mana-mavi',tip:'saglar'}]},
  { id:'tapinak-fennin', baslik:'Fennin Tapınağı (Kırmızı)', kategori:'bina', ikon:'🔥',
    ozet:'Kırmızı mana — ateş/saldırı okulu.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'mana-kirmizi',tip:'saglar'}]},
  { id:'tapinak-tunare', baslik:'Tunare Tapınağı (Yeşil)', kategori:'bina', ikon:'🌿',
    ozet:'Yeşil mana — doğa/üretim okulu.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'mana-yesil',tip:'saglar'}]},
  { id:'buyucu-kulesi', baslik:'Büyücü Kulesi', kategori:'bina', ikon:'🗼',
    ozet:'Büyü öğrenme + hazırlama.',
    stats:{ MaxAdet:5 },
    aciklama:'1 kule = Çağ 1 büyüleri, 5 kule = Çağ 5. 28 büyü, 10 kademe.',
    baglantilar:[{id:'mana-beyaz',tip:'gereklilik'},{id:'buyu-sistem',tip:'ilgili'}]},
  { id:'surlar', baslik:'Surlar', kategori:'bina', ikon:'🏰',
    ozet:'Kale savunması — saldırıda %20 zirh bonusu.',
    baglantilar:[{id:'kale-bonus',tip:'saglar'}]},
  { id:'kule-okcu', baslik:'Okçu Kulesi', kategori:'bina', ikon:'🗼',
    ozet:'Okçu sanal birim — savunmaya ekstra saldırı.',
    stats:{ ATK:50, Tur:'1-3' },
    baglantilar:[{id:'okcu',tip:'ilgili'}]},
  { id:'istihbarat', baslik:'İstihbarat Binası', kategori:'bina', ikon:'🏛️',
    ozet:'Casus üretim merkezi.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'casus-sistem',tip:'ilgili'}]},
  { id:'meydan', baslik:'Şehir Meydanı', kategori:'bina', ikon:'🏛️',
    ozet:'Şehir morali pasif bonus +30.',
    baglantilar:[{id:'sehir-moral',tip:'saglar'}]},
  { id:'taverna', baslik:'Taverna', kategori:'bina', ikon:'🍺',
    ozet:'Şehir morali +40 pasif bonus.',
    baglantilar:[{id:'sehir-moral',tip:'saglar'}]},
  { id:'akademi', baslik:'Akademi', kategori:'bina', ikon:'📚',
    ozet:'GPS Eğitim alanı — 5000 nüfus kapsamı.',
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'gps',tip:'saglar'}]},
  { id:'katedral', baslik:'Katedral', kategori:'bina', ikon:'⛪',
    ozet:'Şehir binası — moral +60, 5000 kapsam.',
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'sehir-moral',tip:'saglar'},{id:'gps',tip:'ilgili'}]},

  // ═══ KAYNAKLAR (10) ═══
  { id:'altin', baslik:'Altın', kategori:'kaynak', ikon:'🪙',
    ozet:'Evrensel birim.',
    aciklama:'Vergi, ticaret, ganimet, sandık ile kazanılır. Ordu maaşı altınla ödenir; ödenmeyince Ordu Morali -10.',
    baglantilar:[{id:'vergi',tip:'saglar'},{id:'ordu-maas',tip:'ilgili'}]},
  { id:'odun', baslik:'Odun', kategori:'kaynak', ikon:'🌲',
    ozet:'Temel hammadde. Kereste ve bina maliyeti.',
    baglantilar:[{id:'oduncu',tip:'gereklilik'},{id:'kereste',tip:'ilgili'}]},
  { id:'metal', baslik:'Metal', kategori:'kaynak', ikon:'⚙️',
    ozet:'Ocak madeni. İşlenmiş metal için kaynak.',
    baglantilar:[{id:'ocak',tip:'gereklilik'},{id:'islenmis',tip:'ilgili'}]},
  { id:'bugday', baslik:'Buğday', kategori:'kaynak', ikon:'🌾',
    ozet:'Yemek temeli. Tarla → Fırın → Ekmek.',
    baglantilar:[{id:'tarla',tip:'gereklilik'},{id:'ekmek',tip:'ilgili'}]},
  { id:'balik', baslik:'Balık', kategori:'kaynak', ikon:'🐟',
    ozet:'İkinci yemek kaynağı.', baglantilar:[{id:'balikci',tip:'gereklilik'}]},
  { id:'kereste', baslik:'Kereste', kategori:'kaynak', ikon:'🪵',
    ozet:'İşlenmiş odun. Yüksek seviye bina için.',
    baglantilar:[{id:'odun',tip:'gereklilik'}]},
  { id:'islenmis', baslik:'İşlenmiş Metal', kategori:'kaynak', ikon:'🔩',
    ozet:'Yüksek seviye bina + birim maliyeti.',
    baglantilar:[{id:'metal',tip:'gereklilik'}]},
  { id:'at', baslik:'At', kategori:'kaynak', ikon:'🐎',
    ozet:'Süvari temel bileşeni. Ahır üretir. 1 at = 50 çiğ et (manuel kesim).',
    baglantilar:[{id:'ahir',tip:'gereklilik'},{id:'sovalye',tip:'ilgili'}]},
  { id:'kurt', baslik:'Kurt', kategori:'kaynak', ikon:'🐺',
    ozet:'Kötü taraf süvari atı yerine kurt.',
    baglantilar:[{id:'ahir',tip:'gereklilik'}]},
  { id:'asker', baslik:'Asker (Ham)', kategori:'kaynak', ikon:'🎖️',
    ozet:'Ünite eğitimi için ham nüfus.',
    aciklama:'Köylülerden dönüştürülür. Geri köylüye çevrilebilir.',
    baglantilar:[{id:'koylu',tip:'gereklilik'},{id:'nufus',tip:'ilgili'}]},
  { id:'koylu', baslik:'Köylü', kategori:'kaynak', ikon:'👨‍🌾',
    ozet:'Temel nufus birimi. Vergi öder.',
    aciklama:'Asker/işçi/worshipper\'a dönüştürülebilir. Worshipper tek yön (geri dönüşüm yok).',
    baglantilar:[{id:'vergi',tip:'saglar'},{id:'asker',tip:'sonra'}]},
  { id:'isci', baslik:'İşçi', kategori:'kaynak', ikon:'⛏️',
    ozet:'5 tip: oduncu, madenci, çiftçi, balıkçı, tüccar.',
    baglantilar:[{id:'koylu',tip:'gereklilik'}]},
  { id:'mana-beyaz', baslik:'Beyaz Mana', kategori:'kaynak', ikon:'⚪',
    ozet:'İyileşme & buff büyüleri.',
    baglantilar:[{id:'tapinak-rathe',tip:'gereklilik'}]},
  { id:'mana-kirmizi', baslik:'Kırmızı Mana', kategori:'kaynak', ikon:'🔴',
    ozet:'Ateş & saldırı büyüleri.',
    baglantilar:[{id:'tapinak-fennin',tip:'gereklilik'}]},
  { id:'mana-mavi', baslik:'Mavi Mana', kategori:'kaynak', ikon:'🔵',
    ozet:'Buz & soğuk büyüleri.',
    baglantilar:[{id:'tapinak-xegony',tip:'gereklilik'}]},
  { id:'mana-yesil', baslik:'Yeşil Mana', kategori:'kaynak', ikon:'🟢',
    ozet:'Doğa & üretim büyüleri.',
    baglantilar:[{id:'tapinak-tunare',tip:'gereklilik'}]},
  { id:'gizlilik', baslik:'Gizlilik', kategori:'kaynak', ikon:'🎭',
    ozet:'Lonca üretir. Casus operasyonu ekonomisi.',
    baglantilar:[{id:'casus-sistem',tip:'saglar'}]},
  { id:'buyulu-yumurta', baslik:'Büyülü Yumurta', kategori:'kaynak', ikon:'🥚',
    ozet:'Büyülü tarla üretir. Ejderha için.',
    baglantilar:[{id:'buyulu-tarla',tip:'gereklilik'},{id:'ejderha',tip:'saglar'}]},
  { id:'nufus', baslik:'Nüfus', kategori:'kaynak', ikon:'👥',
    ozet:'Ev/Köy/Kasaba kapasitesi. Tek doğruluk kaynağı: /api/game/nufus',
    aciklama:'4 tip: Köylü · Asker · İşçi · Worshipper. Workers.total + Unite toplamı = nüfus.',
    baglantilar:[{id:'koylu',tip:'ornek'},{id:'isci',tip:'ornek'}]},

  // ═══ SAVAS (5) ═══
  { id:'savas-motor', baslik:'6 Turlu Savaş Motoru', kategori:'savas', ikon:'⚔️',
    ozet:'Palantis\'in kalbi.',
    stats:{ Tur:6, Saf:4 },
    aciklama:'Tur 1-2: saf_1. Tur 3: saf_1+2. Tur 4: +saf_3. Tur 5-6: tüm saflar.',
    baglantilar:[{id:'savas-saf',tip:'ilgili'},{id:'zirh-iska',tip:'ilgili'},{id:'ordu-moral',tip:'ilgili'},{id:'kale-bonus',tip:'ilgili'}]},
  { id:'savas-saf', baslik:'Saf Dizilimi (4 saf)', kategori:'savas', ikon:'🪖',
    ozet:'Hangi birim hangi safta? = strateji.',
    aciklama:'Her tipten 1 birim 1 safa. Adet farketmez. Saf 1 ön hat, Saf 4 korumalı.',
    baglantilar:[{id:'savas-motor',tip:'ilgili'},{id:'piyade',tip:'ornek'},{id:'okcu',tip:'ornek'}]},
  { id:'zirh-iska', baslik:'Zırh & İska (v1.14.0.45)', kategori:'savas', ikon:'🛡️',
    ozet:'Birim bazlı — her ünite kendi zırhıyla.',
    aciklama:'Zırh artık havuz değil: hasar / (1 + zırh/50). İska deterministik: atk × (1 - iska/100). Simülatör tutarlı.',
    baglantilar:[{id:'savas-motor',tip:'ilgili'},{id:'paladin',tip:'ornek'}]},
  { id:'kale-bonus', baslik:'Kale Bonusu', kategori:'savas', ikon:'🏰',
    ozet:'Savunan tarafın tüm zırhları +%20.',
    baglantilar:[{id:'surlar',tip:'gereklilik'},{id:'savas-motor',tip:'ilgili'}]},
  { id:'ordu-maas', baslik:'Ordu Maaşı', kategori:'savas', ikon:'💸',
    ozet:'Her saat ödenir. Maaş yoksa → Ordu Morali -10.',
    baglantilar:[{id:'altin',tip:'gereklilik'},{id:'ordu-moral',tip:'ilgili'}]},

  // ═══ BUYU (7) ═══
  { id:'buyu-sistem', baslik:'Büyü Sistemi (28 büyü)', kategori:'buyu', ikon:'🔮',
    ozet:'10 kademe, 4 renk mana, 5 çağ.',
    stats:{ Büyü:28, Kademe:10, Renk:4 },
    aciklama:'Mistik Atak, Motivasyon, Ejderha Sevinci, Hipnoz, Sadakat, Yakarış... Mana maliyeti v1.13.70.2 ile ×10.',
    baglantilar:[{id:'buyucu-kulesi',tip:'gereklilik'},{id:'mana-beyaz',tip:'gereklilik'},{id:'bilge',tip:'ilgili'}]},
  { id:'buyu-mistik-atak', baslik:'Mistik Atak', kategori:'buyu', ikon:'💥',
    ozet:'Savaşta saldırı birimlerin ATK +3, DEF -6.',
    aciklama:'Savaş simülatöründe +3/-6 offset. Karmaşık.',
    baglantilar:[{id:'buyu-sistem',tip:'ilgili'},{id:'savas-motor',tip:'ilgili'}]},
  { id:'buyu-ejderha-sevinci', baslik:'Ejderha Sevinci', kategori:'buyu', ikon:'🐲',
    ozet:'Kendine atılır. Şehir morali +X, 6h cooldown.',
    aciklama:'SADECE şehir moralini artırır. Ordu moraline HİÇBİR etkisi yok.',
    baglantilar:[{id:'sehir-moral',tip:'saglar'}]},
  { id:'buyu-motivasyon', baslik:'Motivasyon', kategori:'buyu', ikon:'💪',
    ozet:'Buff — ordu morali artırır (müttefike).',
    baglantilar:[{id:'ordu-moral',tip:'saglar'}]},
  { id:'buyu-hipnoz', baslik:'Hipnoz', kategori:'buyu', ikon:'🌀',
    ozet:'Hedef ordusunun moralini düşürür.',
    baglantilar:[{id:'ordu-moral',tip:'ilgili'}]},
  { id:'bilge', baslik:'Bilge Sistemi', kategori:'buyu', ikon:'🧙',
    ozet:'4 bilge, 336 PG\'de dünya bilgesi değişir.',
    aciklama:'Her 168 PG seçim. Bilge 2× mana verir. Cooldown global.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'tapinak-rathe',tip:'ilgili'},{id:'buyu-sistem',tip:'ilgili'}]},
  { id:'parsomen', baslik:'Parşömen', kategori:'buyu', ikon:'📜',
    ozet:'Okuyarak yeni büyü öğrenmenin yolu.',
    aciklama:'Sandık, Büyü Dükkanı veya savaş ganimetinden çıkar. Büyücü kulesinde okunur.',
    baglantilar:[{id:'buyucu-kulesi',tip:'ilgili'}]},

  // ═══ CASUS (3) ═══
  { id:'casus-sistem', baslik:'Casus Sistemi (11 operasyon)', kategori:'casus', ikon:'🕵️',
    ozet:'İstihbarattan eğitilir. 11 görev tipi.',
    aciklama:'İncele, Hırsızlık, Kargaşa, Katliam, Sabotaj, Parşömen Çal... Can + deneyim + ölüm.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'istihbarat',tip:'gereklilik'},{id:'gizlilik',tip:'gereklilik'}]},
  { id:'casus-incele', baslik:'İncele (Casus)', kategori:'casus', ikon:'🔍',
    ozet:'Hedef krallığın kaynak/ordu/bina bilgisi.',
    baglantilar:[{id:'casus-sistem',tip:'ilgili'}]},
  { id:'casus-sabotaj', baslik:'Sabotaj (Casus)', kategori:'casus', ikon:'💥',
    ozet:'Hedef binasına %X hasar verir.',
    baglantilar:[{id:'casus-sistem',tip:'ilgili'}]},

  // ═══ CAG (5) ═══
  { id:'cag', baslik:'5 Çağ Sistemi', kategori:'cag', ikon:'⏳',
    ozet:'Sonatas → Heonteas → Kronitas → Rashnotor → Noxara',
    aciklama:'1 PG = 1 gerçek saat. Her çağ yeni binalar/birimler/büyüler.',
    baglantilar:[{id:'cag1',tip:'ornek'},{id:'cag2',tip:'ornek'}]},
  { id:'cag1', baslik:'I. Çağ — Sonatas', kategori:'cag', ikon:'🌅',
    ozet:'Başlangıç çağı. Temel ekonomi.',
    aciklama:'Koruma: savunan çağ < 2 ise saldırılamaz.',
    baglantilar:[{id:'cag',tip:'ilgili'},{id:'piyade',tip:'ornek'}]},
  { id:'cag2', baslik:'II. Çağ — Heonteas', kategori:'cag', ikon:'🏹',
    ozet:'Askeri açılım. Ahir, Tapınak, İstihbarat.',
    baglantilar:[{id:'cag',tip:'ilgili'},{id:'sovalye',tip:'ornek'}]},
  { id:'cag3', baslik:'III. Çağ — Kronitas', kategori:'cag', ikon:'🔮',
    ozet:'Büyü + Guild açılımı.',
    baglantilar:[{id:'cag',tip:'ilgili'},{id:'buyulu-tarla',tip:'ornek'},{id:'guild',tip:'ornek'}]},
  { id:'cag4', baslik:'IV. Çağ — Rashnotor', kategori:'cag', ikon:'⚔️',
    ozet:'Elit birimler + Ejderha.',
    baglantilar:[{id:'cag',tip:'ilgili'},{id:'ejderha',tip:'ornek'}]},
  { id:'cag5', baslik:'V. Çağ — Noxara', kategori:'cag', ikon:'🌑',
    ozet:'Usta seviye. Kusatma + sezon sonu.',
    baglantilar:[{id:'cag',tip:'ilgili'}]},

  // ═══ MORAL (4) ═══
  { id:'sehir-moral', baslik:'Şehir Morali 🏛️', kategori:'moral', ikon:'😊',
    ozet:'Halkın memnuniyeti (0-5000). Vergi ile.',
    stats:{ Max:'Çağ5=5000', Min:-1500 },
    aciklama:'**ORDU MORALİ DEĞİL!** Vergi cezası, açlık, festival, bina bonusu etkiler. Düşük → işçi üretimi düşer + köylü kaçar.',
    baglantilar:[{id:'vergi',tip:'ilgili'},{id:'gps',tip:'ilgili'},{id:'ordu-moral',tip:'karsilastir'}]},
  { id:'ordu-moral', baslik:'Ordu Morali ⚔️', kategori:'moral', ikon:'🎖️',
    ozet:'Askerin savaş gücü (0-100). Maaş ile.',
    aciklama:'**ŞEHİR MORALİ İLE HİÇBİR İLİŞKİSİ YOK!** Maaş öderse +5, ödemezse -10. ATK/DEF çarpanı = moral/100 (MIN 0.2).',
    baglantilar:[{id:'ordu-maas',tip:'ilgili'},{id:'sehir-moral',tip:'karsilastir'}]},
  { id:'gps', baslik:'GPS (5 İlgi Alanı)', kategori:'moral', ikon:'📊',
    ozet:'Populasyon Seviyesi.',
    aciklama:'5 alan: Eğitim/Bilgi/Kültür/Eğlence/Şehir. Ortalama kapsama %. GPS ≥ %90 → +4 moral/saat.',
    baglantilar:[{id:'sehir-moral',tip:'ilgili'}]},
  { id:'vergi', baslik:'Vergi Sistemi (5 plug-in)', kategori:'moral', ikon:'💰',
    ozet:'Admin seçer: Klasik/GPS/Progressive/Dinamik/Premium.',
    aciklama:'Vergi oranı yüksek → şehir morali düşer. Cezalar katlanarak artar.',
    baglantilar:[{id:'altin',tip:'saglar'},{id:'sehir-moral',tip:'ilgili'}]},
  { id:'festival', baslik:'Festival', kategori:'moral', ikon:'🎉',
    ozet:'Altın + ekmek → şehir morali +X.',
    aciklama:'3 seviye: Küçük/Büyük/Kraliyet. Eski Palantis: +200/+500/+1500.',
    baglantilar:[{id:'sehir-moral',tip:'saglar'}]},

  // ═══ GUILD (4) ═══
  { id:'guild', baslik:'Guild Sistemi', kategori:'guild', ikon:'🏰',
    ozet:'Oyuncu toplulukları. Ortak şehir + ordu.',
    aciklama:'Guild taraf kilitli (v1.14.0.44). Faz 1: üyelik. Faz 2: bina/ordu. Faz 3: Kadim kuşatma.',
    kilit:{aktif:true,sart:{tip:'cag',deger:3}},
    baglantilar:[{id:'diplomasi',tip:'ilgili'},{id:'tech-tree',tip:'ilgili'},{id:'kadim',tip:'ilgili'}]},
  { id:'diplomasi', baslik:'Diplomasi (v1.14.0.30)', kategori:'guild', ikon:'🤝',
    ozet:'4 durum: BARIŞ / ANTLAŞMA / SAVAŞ / TABİYET.',
    aciklama:'İhanet debuff: savaşta -%6 ATK/DEF. Tabiyet: bağlı üretiminin %30\'u Hakim\'e.',
    baglantilar:[{id:'guild',tip:'ilgili'}]},
  { id:'tech-tree', baslik:'Guild Tech Tree', kategori:'guild', ikon:'🔬',
    ozet:'5 teknoloji — üretim/savunma/atk/inşaat/ekonomi.',
    baglantilar:[{id:'guild',tip:'ilgili'}]},
  { id:'kusatma', baslik:'Kadim Kuşatma', kategori:'guild', ikon:'⚔️',
    ozet:'Guild ortak saldırı — kadim şehir ele geçirme.',
    kilit:{aktif:true,sart:{tip:'cag',deger:4}},
    baglantilar:[{id:'kadim',tip:'ilgili'},{id:'guild',tip:'gereklilik'}]},

  // ═══ KADIM (3) ═══
  { id:'kadim', baslik:'Kadim Şehirler', kategori:'kadim', ikon:'🏺',
    ozet:'Aurium (Işık) + Gorathul (Karanlık).',
    aciklama:'Mananın, atın, gizliliğin kadim kaynakları. Ticaret → 240 PG sonra çapraz eş saldırır.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'at',tip:'saglar'},{id:'mana-beyaz',tip:'saglar'},{id:'gizlilik',tip:'saglar'}]},
  { id:'aurium', baslik:'Aurium', kategori:'kadim', ikon:'☀️',
    ozet:'Işık kadim şehri. X=15 Y=8.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'kadim',tip:'ilgili'}]},
  { id:'gorathul', baslik:'Gorathul', kategori:'kadim', ikon:'🌑',
    ozet:'Karanlık kadim şehri. X=185 Y=42.',
    kilit:{aktif:true,sart:{tip:'cag',deger:2}},
    baglantilar:[{id:'kadim',tip:'ilgili'}]},

  // ═══ IRKLAR (9 — genel + 8) ═══
  { id:'irk', baslik:'8 Irk (İyi / Kötü)', kategori:'irk', ikon:'👑',
    ozet:'İnsan/Elf/Cüce/Bucukluk × Kara Elf/Ork/Ogre/Undead',
    aciklama:'Taraf kilitli. ATK/DEF/kaynak bonusu. Paladin iyi, Kara Şövalye kötü.',
    baglantilar:[{id:'insan',tip:'ornek'},{id:'kara-elf',tip:'ornek'}]},
  { id:'insan', baslik:'İnsan', kategori:'irk', ikon:'👑',
    ozet:'Dengeli ırk. Her alanda hafif bonus.',
    stats:{ ATK:'+2', DEF:'+2', Altın:'+2%', Odun:'+2%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'elf', baslik:'Elf', kategori:'irk', ikon:'🌿',
    ozet:'Doğa ve büyü ustası.',
    stats:{ Odun:'+5%', Mana:'+5%', ATK:'+5' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'cuce', baslik:'Cüce', kategori:'irk', ikon:'⚒️',
    ozet:'Madenci ve zanaatkar.',
    stats:{ Metal:'+5%', DEF:'+5', BinaFiyat:'-10%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'bucukluk', baslik:'Bucukluk', kategori:'irk', ikon:'🎭',
    ozet:'Kurnaz tüccar. Casusluk uzmanı.',
    stats:{ Altın:'+7%', Gizlilik:'+5%', CasusBaşarı:'+5%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'kara-elf', baslik:'Kara Elf', kategori:'irk', ikon:'🖤',
    ozet:'Karanlık büyü ve zehir.',
    stats:{ Gizlilik:'+8%', ZehirATK:'+10%', Mana:'+5%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'ork', baslik:'Ork', kategori:'irk', ikon:'💪',
    ozet:'Ham güç ve savaş.',
    stats:{ ATK:'+8', Metal:'+5%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'ogre', baslik:'Ogre', kategori:'irk', ikon:'👹',
    ozet:'Dev güç, yavaş, yıkıcı.',
    stats:{ ATK:'+10', DEF:'+5', BinaYıkım:'+15%' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
  { id:'undead', baslik:'Undead', kategori:'irk', ikon:'💀',
    ozet:'Ölümsüz, soğuk.',
    stats:{ ATK:'+8', DEF:'+8' },
    baglantilar:[{id:'irk',tip:'ilgili'}]},
];

window.CODEX_BAG_LABEL = {
  gereklilik: { label:'Gereklilik',  ikon:'⬅',  renk:'#e74c3c' },
  saglar:     { label:'Sağlar',      ikon:'➜',  renk:'#2ecc71' },
  ilgili:     { label:'İlgili',      ikon:'◌',  renk:'#3498db' },
  karsilastir:{ label:'Karşılaştır', ikon:'⚖',  renk:'#d4a257' },
  sonra:      { label:'Sonrası',     ikon:'→',  renk:'#9b59b6' },
  ornek:      { label:'Örnek',       ikon:'◆',  renk:'#1abc9c' },
  'ornek-kilit':{label:'Örnek (Kilitli)', ikon:'◆', renk:'#95a5a6' },
};

// Global helper — node id'den obje bul
window.codexGetNode = function(id) {
  return window.CODEX_NODES.find(n => n.id === id);
};
